name: run-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # يشغل كل 30 دقيقة

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      # ========= مهم: إنشاء ملف Google Key =========
      - name: Create gcp key
        run: |
          echo '${{ secrets.GCP_KEY }}' > gcp-key.json

      # ========= تشغيل البوت =========
      - name: Run bot
        env:
          ZOHO_EMAIL: ${{ secrets.ZOHO_EMAIL }}
          ZOHO_PASSWORD: ${{ secrets.ZOHO_PASSWORD }}
        run: python warmup_bot.py
